#pragma once

#include <windows.h>
#include <vector>
#include <cstdint>
#include <algorithm>
#include "PdfDocument.h"
#include "InvertSettings.h"
#include "LayerSystem.h"
#include "PdfViewState.h"
#include "PdfThumbnailRail.h"

class AppWindow {
public:
    bool Create(HINSTANCE instance);
    int Run();
    void SelectPageFromThumbnail(int page) { if (!pdf_.IsOpen() || page < 0 || page >= pdf_.PageCount()) return; pageIndex_=page; scrollY_=0; RenderCurrentPage(); Refresh(); }
    void Refresh() noexcept { InvalidateRect(hwnd_,nullptr,FALSE); PdfThumbnailRail::Refresh(hwnd_); }
    HWND hwnd() const noexcept { return hwnd_; }
    PdfDocument& pdf() noexcept { return pdf_; }
    const PdfDocument& pdf() const noexcept { return pdf_; }
    int pageIndex() const noexcept { return pageIndex_; }
    bool invertEnabled() const noexcept { return invert_; }
private:
    static LRESULT CALLBACK WindowProc(HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam);
    LRESULT HandleMessage(UINT message, WPARAM wParam, LPARAM lParam);
    void Paint(HDC hdc); void DrawToolbarButton(const DRAWITEMSTRUCT* dis); void OpenPdf(); void RenderCurrentPage(); void ApplyInvert(); void CreateToolbar(); void LayoutToolbar(int width); void UpdateScrollBar(); void UpdateToolbarText(); void ChangeZoom(double factor); void ScrollBy(int delta); void SetInvert(bool enabled); void GoPage(int delta); void ChooseBackground(); void FitPage(); void FitWidth(); void ShowLayerMenu(); void UpdateLayerGeometry(); void SetMosuanTool(MosuanTool tool);
    HWND hwnd_=nullptr; HINSTANCE instance_=nullptr; PdfDocument pdf_; LayerSystem layers_; std::vector<std::uint8_t> pixels_; PdfViewState pdfView_; int pageIndex_=0; int renderWidth_=0; int renderHeight_=0; int scrollY_=0; double zoom_=1.0; bool fitWidth_=false; bool invert_=false; bool dashMode_=false; bool oneStrokeMode_=true; int penColorIndex_=0; int penWidthIndex_=1; MosuanTool activeTool_=MosuanTool::Pen; InvertSettings invertSettings_;
    HWND openButton_=nullptr,saveButton_=nullptr,zoomOutButton_=nullptr,zoomLabel_=nullptr,zoomInButton_=nullptr,fitWidthButton_=nullptr,panButton_=nullptr,penButton_=nullptr,rulerButton_=nullptr,lassoButton_=nullptr,eraserButton_=nullptr,lineButton_=nullptr,colorBlackButton_=nullptr,colorRedButton_=nullptr,colorBlueButton_=nullptr,thinButton_=nullptr,mediumButton_=nullptr,thickButton_=nullptr,dashButton_=nullptr,oneStrokeButton_=nullptr,pageLabel_=nullptr; HFONT toolbarFont_=nullptr;
};

namespace PdfThumbnailDetail {
inline constexpr wchar_t kClassName[]=L"PDFDarkReaderThumbnailRail"; inline constexpr UINT_PTR kTimer=1; inline constexpr int kHeaderHeight=34,kThumbW=82,kThumbH=108,kGap=10,kLeft=15,kTopPadding=10;
struct Thumbnail{int width=0,height=0;std::vector<std::uint8_t> pixels;}; struct State{HWND rail=nullptr,parent=nullptr;AppWindow* app=nullptr;int scrollY=0,cachedPageCount=-1;std::unordered_map<int,Thumbnail> cache;}; inline State g; inline HHOOK hook=nullptr; inline bool registered=false;
inline void Fill(HDC d,const RECT&r,COLORREF c){HBRUSH b=CreateSolidBrush(c);FillRect(d,&r,b);DeleteObject(b);} inline void Resize(){if(!g.rail||!g.parent)return;RECT r{};GetClientRect(g.parent,&r);MoveWindow(g.rail,0,PdfThumbnailRail::kTop,PdfThumbnailRail::kWidth,(std::max)(1,(int)r.bottom-PdfThumbnailRail::kTop),TRUE);}
inline Thumbnail* Get(AppWindow&a,int p){int n=a.pdf().PageCount();if(n!=g.cachedPageCount){g.cache.clear();g.cachedPageCount=n;g.scrollY=0;}auto i=g.cache.find(p);if(i!=g.cache.end())return&i->second;float pw=1,ph=1;if(!a.pdf().PageSize(p,pw,ph))return nullptr;double s=std::min((kThumbW-8.0)/pw,(kThumbH-8.0)/ph);Thumbnail t;t.width=(std::max)(1,(int)(pw*s));t.height=(std::max)(1,(int)(ph*s));if(!a.pdf().RenderPage(p,t.width,t.height,t.pixels))return nullptr;auto[q,_]=g.cache.emplace(p,std::move(t));return&q->second;}
inline LRESULT CALLBACK RailProc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_NCCREATE){auto*c=(CREATESTRUCTW*)l;SetWindowLongPtrW(h,GWLP_USERDATA,(LONG_PTR)c->lpCreateParams);return TRUE;}auto*a=(AppWindow*)GetWindowLongPtrW(h,GWLP_USERDATA);switch(m){case WM_ERASEBKGND:return 1;case WM_TIMER:Resize();InvalidateRect(h,nullptr,FALSE);return 0;case WM_MOUSEWHEEL:{if(!a)return 0;RECT r{};GetClientRect(h,&r);int maxs=(std::max)(0,kTopPadding+a->pdf().PageCount()*(kThumbH+kGap)-((std::max)(1,(int)r.bottom-kHeaderHeight)));g.scrollY=std::clamp(g.scrollY-(GET_WHEEL_DELTA_WPARAM(w)/WHEEL_DELTA)*54,0,maxs);InvalidateRect(h,nullptr,FALSE);return 0;}case WM_LBUTTONDOWN:{if(!a||!a->pdf().IsOpen())return 0;int y=GET_Y_LPARAM(l),row=y-(kHeaderHeight+kTopPadding)+g.scrollY,step=kThumbH+kGap;if(row<0)return 0;int p=row/step;if(row%step>=kThumbH||p<0||p>=a->pdf().PageCount())return 0;a->SelectPageFromThumbnail(p);SetFocus(a->hwnd());return 0;}case WM_PAINT:{PAINTSTRUCT ps{};HDC d=BeginPaint(h,&ps);RECT r{};GetClientRect(h,&r);Fill(d,r,RGB(24,26,31));if(!a||!a->pdf().IsOpen()){EndPaint(h,&ps);return 0;}SetBkMode(d,TRANSPARENT);SetTextColor(d,RGB(190,194,202));RECT t{0,0,kThumbW+30,kHeaderHeight};DrawTextW(d,L"PDF",-1,&t,DT_CENTER|DT_VCENTER|DT_SINGLELINE);int n=a->pdf().PageCount(),vp=(std::max)(1,(int)r.bottom-kHeaderHeight),maxs=(std::max)(0,kTopPadding+n*(kThumbH+kGap)-vp);g.scrollY=std::clamp(g.scrollY,0,maxs);int first=(std::max)(0,(g.scrollY-kTopPadding)/(kThumbH+kGap)),last=(std::min)(n-1,(g.scrollY+vp)/(kThumbH+kGap)+1);for(int p=first;p<=last;++p){int y=kHeaderHeight+kTopPadding+p*(kThumbH+kGap)-g.scrollY;if(y>r.bottom||y+kThumbH<kHeaderHeight)continue;RECT card{kLeft,y,kLeft+kThumbW,y+kThumbH};bool active=p==a->pageIndex();Fill(d,card,active?RGB(49,55,67):RGB(33,36,42));HPEN pen=CreatePen(PS_SOLID,active?2:1,active?RGB(100,150,235):RGB(62,66,74));HGDIOBJ op=SelectObject(d,pen),ob=SelectObject(d,GetStockObject(NULL_BRUSH));Rectangle(d,card.left,card.top,card.right,card.bottom);SelectObject(d,ob);SelectObject(d,op);DeleteObject(pen);if(auto*x=Get(*a,p);x&&!x->pixels.empty()){BITMAPINFO b{};b.bmiHeader.biSize=sizeof(BITMAPINFOHEADER);b.bmiHeader.biWidth=x->width;b.bmiHeader.biHeight=-x->height;b.bmiHeader.biPlanes=1;b.bmiHeader.biBitCount=32;b.bmiHeader.biCompression=BI_RGB;StretchDIBits(d,card.left+(kThumbW-x->width)/2,card.top+4,x->width,x->height,0,0,x->width,x->height,x->pixels.data(),&b,DIB_RGB_COLORS,SRCCOPY);}wchar_t num[16]{};wsprintfW(num,L"%d",p+1);SetTextColor(d,RGB(175,180,190));RECT lab{card.left,card.bottom-18,card.right,card.bottom};DrawTextW(d,num,-1,&lab,DT_CENTER|DT_VCENTER|DT_SINGLELINE);}EndPaint(h,&ps);return 0;}case WM_DESTROY:KillTimer(h,kTimer);return 0;}return DefWindowProcW(h,m,w,l);}
inline void Ensure(HWND parent){if(!parent)return;if(g.rail&&IsWindow(g.rail)){Resize();return;}g.parent=parent;g.app=(AppWindow*)GetWindowLongPtrW(parent,GWLP_USERDATA);WNDCLASSEXW wc{};wc.cbSize=sizeof(wc);wc.hInstance=GetModuleHandleW(nullptr);wc.lpfnWndProc=RailProc;wc.lpszClassName=kClassName;wc.hCursor=LoadCursorW(nullptr,IDC_ARROW);if(!registered){RegisterClassExW(&wc);registered=true;}g.rail=CreateWindowExW(0,kClassName,L"",WS_CHILD|WS_VISIBLE,0,PdfThumbnailRail::kTop,PdfThumbnailRail::kWidth,500,parent,nullptr,wc.hInstance,g.app);Resize();SetTimer(g.rail,kTimer,250,nullptr);InvalidateRect(g.rail,nullptr,FALSE);}
inline LRESULT CALLBACK CbtProc(int c,WPARAM w,LPARAM){if(c==HCBT_ACTIVATE){HWND h=(HWND)w;wchar_t cls[128]{};GetClassNameW(h,cls,128);if(lstrcmpW(cls,L"PDFDarkReaderWindow")==0)Ensure(h);}return CallNextHookEx(hook,c,w,0);} struct HookInstaller{HookInstaller(){hook=SetWindowsHookExW(WH_CBT,CbtProc,nullptr,GetCurrentThreadId());}~HookInstaller(){if(hook)UnhookWindowsHookEx(hook);}};inline HookInstaller installer;
}
inline void PdfThumbnailRail::Install(){if(!PdfThumbnailDetail::hook)PdfThumbnailDetail::hook=SetWindowsHookExW(WH_CBT,PdfThumbnailDetail::CbtProc,nullptr,GetCurrentThreadId());}
inline void PdfThumbnailRail::Ensure(HWND p){PdfThumbnailDetail::Ensure(p);} inline void PdfThumbnailRail::Resize(HWND p){if(p==PdfThumbnailDetail::g.parent)PdfThumbnailDetail::Resize();} inline void PdfThumbnailRail::Refresh(HWND p){if(p==PdfThumbnailDetail::g.parent&&PdfThumbnailDetail::g.rail)InvalidateRect(PdfThumbnailDetail::g.rail,nullptr,FALSE);} inline void PdfThumbnailRail::ResetCache(){PdfThumbnailDetail::g.cache.clear();PdfThumbnailDetail::g.cachedPageCount=-1;PdfThumbnailDetail::g.scrollY=0;if(PdfThumbnailDetail::g.rail)InvalidateRect(PdfThumbnailDetail::g.rail,nullptr,FALSE);}
